version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Reservation

  user-service:
    build: ./user_service
    container_name: user_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3001

  reservation-service:
    build: ./reservation_service
    container_name: reservation_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3002

  notification-service:
    build: ./notification_service
    container_name: notification_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3003

  salle-service:
    build: ./salle_service
    container_name: salle_service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3004

  historique-service:
    build: ./historique_service
    container_name: historique_service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3005

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  mongodb_data:
