version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Reservation

  user-service:
    build: ./user_service
    container_name: user_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3001

  reservation-service:
    build: ./reservation_service
    container_name: reservation_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - kafka
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - KAFKA_BROKER=kafka:9092
      - PORT=3002

  notification-service:
    build: ./notification_service
    container_name: notification_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3003

  salle-service:
    build: ./salle_service
    container_name: salle_service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3004

  historique-service:
    build: ./historique_service
    container_name: historique_service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://ImenHT:WKeNiqSH3x5zAcay@cluster0.qjhwp.mongodb.net/Reservation
      - PORT=3005

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  mongodb_data:
