replicaCount: 1
autoscaling:
  enabled: false

image:
  repository: imenht/reservation_service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3002

ingress:
    enabled: true
    className: nginx
    annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
    - host: reservation-service.local
      paths:
        - path: /
          pathType: Prefix
    tls: []

podAnnotations: {}
podLabels: {}

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

resources: {}

livenessProbe: {}
readinessProbe: {}

volumeMounts: []
volumes: []

nodeSelector: {}
tolerations: []
affinity: []

